name: Publish to PyPI and TestPyPI
on:
  push:
    branches:
    - master
  release:
    types:
    - published
    - created
    - edited
    - released

jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build netCDF4 pandas pyarrow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build dist
      run: |
        python -m build --sdist --wheel --outdir dist/
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      if: github.release && (github.release.draft == false)
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
